# Generated by Django 4.2.5 on 2023-10-04 07:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StudentInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_first_name', models.CharField(max_length=100)),
                ('student_last_name', models.CharField(max_length=100)),
                ('student_image', models.ImageField(upload_to='students')),
                ('student_roll', models.IntegerField()),
                ('student_registration', models.IntegerField()),
                ('student_age', models.IntegerField()),
                ('student_city', models.CharField(max_length=100)),
                ('student_full_address', models.CharField(max_length=200)),
            ],
        ),
    ]
